### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by rtrimbler** [ThorstenBr/DAN2on3#2]
Are some files missing from the "Apple3SOS.DAN2on3.Config.dsk"? When I copied it over to my system with ADTPro, the only thing on the disk is "DAN2ON3.DRIVER". This is not a bootable disk. (Can also just look at the image in CiderPress.) This text in the README file seems to indicate there should be more: "a separate configuration disk "Apple3SOS.DAN2on3.Config.dsk" is provided for convenience. It provides the same configuration options as known from the controller's Apple II boot menu."

**Comment by ThorstenBr** [comment]
No files are missing. This disk contains a custom bootloader. This is what displays the configuration menu, allowing to select the active volumes of the DAN][ controller card. The bootloader automatically searches for a slot containing the DAN][ card. It shows an error message otherwise (when no card was found).
When you look at the files on the disk then you can only see the driver file. The bootloader is stored in the first two blocks of the disk, these are not part of the SOS filesystem. So neither ADTpro, Ciderpress, nor SOS will show the bootloader as a separate file.

**Comment by rtrimbler** [comment]
Thank you for explaining! I keep getting reminded how much I've forgotten about the inner workings over the years since I was actively using an 8-bit system. Sorry for the confusion.
