### ISSUE TITLE
Bug in a3rompatch.py

### ISSUE THREAD

**Issue by rtrimbler** [ThorstenBr/DAN2on3#5]
I think there is a mistake in a3rompatch.py

line 27 reads "if (i>=0x1FC0)and(i<=0x1FEF):"
but should be "if (i>=0x0FC0)and(i<=0x0FEF):"
0x1FC0 is 8128, so the expression is never true for "range(4096)" and the checksum is not calculated correctly.

The correct value for the byte at (f)6e5 is 0x57.

**Comment by rtrimbler** [comment]
Unfortunately, while this resolves the "ROM" boot test issue, the machine still beeps and drops into the monitor instead of going to the "Dan ][ Press Return" screen. (Currently using a 28C64B-15 eeprom in place of the Apple ROM.)

**Comment by ThorstenBr** [comment]
Thanks! You are absolutely right. The utility isn't considering the address range of the 6522 registers correctly. That's a 16byte range in the ROM, which contains a copyright message. However, these bytes are inaccessible by the Apple /// since the two 6522 VIAs are mapped to this address range - overlaying the ROM area. That's why those bytes must not be considered when calculating the ROM checksum.

It's weird though, since I do not see the issue on my system. Seems something with the power-up reset wasn't properly working with my machine. Indeed the ROM diagnostic routines are only executed when the CONTROL key is NOT pressed. So, the diagnostics are only executed at initial power up. And if you press CTRL-RESET to trigger an additional RESET, then they are not executed.

And if you just press the RESET button (without CONTROL), then the Apple /// only triggers an NMI (not a reset). So the only way to execute the diagnostics is a normal power-up RESET. Seems that's not working as expected on my machine.

Either my mainboard inccorrectly detects that "CONTROL" was pressed, or the mainboard somehow triggers an NMI immediately after RESET. I suspect the latter might be happening. But in both cases the ROM diagnostics would be skipped.

Concerning your second issue: does it drop to monitor on the first RESET only - or does it not work at all now?
The new ROM would drop to monitor if it's unable to load the boot program from the DAN controller ("VOLA3.po" from the first SD card with FAT filesystem).

**Comment by rtrimbler** [comment]
It only drops into the monitor at power-up.  CTRL-RESET at that point, goes
right to the "DAN2ON3: Press Return" screen. From here on, everything works
as expected. I get the volume selector screen, I can boot from DRIVE 1,
etc. For example, if I run the HORSES demo (that you previously provided)
then exit, I see the expected "Insert system disk; press CTRL-RESET". I
press CTRL-RESET and get back to the DAN2ON3: screen, and I can keep on
going like your Youtube demo.

The SD card in slot 1 has a FAT file system and does have this:
"VOLA3_APPLEIII_BOOT_MENU.po". Looks like there is code in the first 3
blocks of that file.

If I hold down the control key at power-on it does seem to skip the
diagnostics (no ram test grid, at least) but it still drops into the
monitor. If I press just RESET at this point the screen goes blank and
nothing happens (until I press ctrl-reset.)

Taking out the second SD card had no effect.

It sure seems like it is having a problem reading the VOLA3.po file.

**Comment by ThorstenBr** [comment]
Ok, I solved the "mystery" with my machine. Was not related to my machine after all. I simply couldn't see any ROM diagnostic failures since it *immediately* continued booting - no matter what. And when it immediately continued, the loaded DAN][ boot program *immediately* wiped the screen. There was absolutely no way for the human eye to even see any diagnostic errors.

Here's my latest version of the ROM binary - fixes the checksum and the issue with a missing loop to block the CPU after an error. I'll also update the release binaries in a bit (I have another nice feature for the DAN][ card pending...).
[A3ROM_DANII.zip](https://github.com/ThorstenBr/DAN2on3/files/13127917/A3ROM_DANII.zip)

So, the only reason why you could see the issue with the invalid checksum in the first place, was that it doesn't successfully load the boot program after a power-up reset. So that's another issue - which I do not have.

Seems the DAN][ controller is somehow stuck (or out of sync) after power-up. When pressing "RESET" alone does not help, then this confirms that the controller is stuck: the RESET button alone does not trigger a hardware reset, but just an 6502 NMI interrupt. The DAN][ controller doesn't know about the NMI. So if it was stuck before, it just remains being stuck.

Pressing CTRL-RESET, however, triggers a full hardware reset: this affects both, the 6502 CPU *and* the DAN][ card.

So there seems to be some kind of power-up issue with your DAN][ card...

Are you using the custom bootloader for the DAN][ controller (which also supports firmware updates), or is the ATMEGA still programmed with the stock Ardunio bootloader?

**Comment by rtrimbler** [comment]
Kind of new to the whole arduino ecosystem. Most likely using the stock
bootloader; I usually build the Apple2Arduino code from the source by
loading it into the arduino (1.8.19) IDE. I upload the code to the
ATmega328 plugged into an Uno clone, then move the '328 to the Dan][ card.
This is a fairly simple operation for me, everything is within arm's reach.

I have 2 Dan][ cards built now; both behave the same way (with respect to
this issue.)

**Comment by rtrimbler** [comment]
Copied the "Apple2Arduino.ino.328p.with_bootloader.hex" file from the
v3.3.3 release to an ATmega328 part using my XGecu T48 programmer. At
power-on there is some LED activity on SD1 and SD2, but the screen just
goes blank. If I press reset, it accesses SD1 for a second or two, then
drops into the monitor. Ctrl-reset behaves like power-on - LEDs blink, then
nothing.
If the Alpha-lock button is down, it boots from the floppy and shows the
volume selector screen, but no files or SD cards.
If I put my "working" code back on the '328 chip with the T48 programmer, I
go back to the previously detailed behavior.

**Comment by rtrimbler** [comment]
After numerous attempts to program the '328p with the v3.3.3 code, I was finally able to get one that *does not* fall into the monitor at power-up. I used an ISP shield that sits on an Uno, and built the code from the Apple2Arduino sources. 

I have not found a way to successfully use the pre-built hex file in the repository. '328s programmed with the stand-alone programmer appear bricked, and the ISP shield shows an error and this message: 
"avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xe0"

Unfortunately, FTP has stopped working again. Note the only change I made to the arduino sketch was in config.h to set the cmd and data ports to 2121 and 2120 respectively (since this has been working for me until just now.)

> $ ftp -a -P 2121 192.168.50.220
> Connected to 192.168.50.220.
> 220 Welcome to DAN][, v3.3.3. Apple ][ Forever!
> 230 Ok
> Remote system type is DAN][.
> ftp> ls
> 421 Service not available, remote server has closed connection.
> 502 Failed
> ftp>

**Comment by ThorstenBr** [comment]
- The stock Arduino bootloader is _not_ going to work with the modified Apple /// ROM. The stock bootloader waits for 1 second for flash programming requests via the UART connection. Only afterwards will it launch the DAN][ firmware. This is good enough when you boot the Apple /// from floppy - since loading from disk takes about 2 seconds, so the ATMEGA is ready in time. But with the modified ROM the Apple /// almost instantly talks to the ATMEGA...
- The custom bootloader replaces the UART connection with the DAN]['s internal port to the 6502. The custom bootloader immediately notices when the Apple /// ROM sends the request to load the boot menu (rather than sending flash update requests). This causes the custom bootloader to immediately proceed with loading the DAN][ firmware (and stop waiting for flash requests). So that's why the new Apple /// ROM wouldn't work with your DAN][ card on power-up: the ATMEGA wasn't ready.

- I'm not quite sure which "ISP shield" you are using. However, if it's an actual ISP shield (rather than just using an Arduino UNO board's builtin USB-to-UART adapter) then this has to work independently of the ATMEGA's flash content. Even if you flashed random data to the ATMEGA, the ISP connection doesn't care what's in flash memory: it still needs to work. If an ISP connection isn't working then either something is broken with the ISP connection itself - or, maybe more likely, the ATMEGA's fuse bits are not programmed correctly.
- You mentioned you are using a XGecu programmer. I don't know this device, but when you load the hex file, you will have to manually enter the ATMEGA fuse bits somewhere (probably a separate dialog or panel in your programmer's software). The fuse bits configure the ATMEGA chip - and these settings are not part of the hex file. The correct fuse bits are mentioned in the DAN][ readme (lfuse 0xFF, hfuse 0xDE, efuse 0xFD). This configures the ATMEGA to an external 16MHz crystal, sets the bootloader size to 512 byte, enables ISP programming etc. The programmer will otherwise set the fuses to the ATMEGA's factory defaults - and those won't work (e.g. incorrect bootloader size, incorrect clock source).
- When you program the Apple2Arduino.ino.328p.with_bootloader.hex and have the correct fuse settings, then see if the self-test works. You can trigger the self-test by removing both SD cards. When you power the DAN][ controller without SD cards, the SD1+2 LEDs should slowy blink three times (in an alternate fashion). If that's not working, then either the hex file or the fuse bits are probably not programmed correctly.

**Comment by rtrimbler** [comment]
I figured out how to set the fuse bits with the XGecu programmer so the
Apple2Arduino.ino.328p.with_bootloader.hex file successfully boots with the
modified A/// boot rom. FTP with this 328p still does not work.

I think you are right that trying to program with the hex file via the ISP
shield didn't work because the fuse bits were never changed.

Honestly don't know why/how, but programming a '328 with the ISP shield and
using nothing but unmodified Apple2Arduino v3.3.3 source code also boots
correctly and FTP works.

My modified boot rom is a 28 pin 28C64 eeprom. It has a few jumper wires
and the 4 "extra" pins overhang the front of the 24 pin motherboard socket.

**Comment by rtrimbler** [comment]
Closing this because the original issue with a3rompatch.py was fixed.

**Comment by ThorstenBr** [comment]
Ok, one step ahead...

The FTP error "502 Failed" indicates that the FTP server received a command it did not understand. Please enable "verbose" output of your FTP client (probably something like "ftp -v ...."), so we can see which command triggered the "502" error.
Make sure that you use "passive FTP". For some FTP client's that's the default, while some use "active FTP" by default - and you may need to set a command-line option to switch to "passive mode" (often "-p").
If an FTP client requested an active connection, the DAN][ FTP server would also reply with "502 Failed" (since it does not understand the respective command).

**Comment by rtrimbler** [comment]
Running Ubuntu 22.04 in windows (WSL). Ftp defaults to passive and verbose, so the -v command doesn't do anything. However, -d shows us this:

```
reidx@GigaH270M:~$ ftp -a  -d 192.168.50.220
setupsockbufsize: rcvbuf_size determined as 1048576
setupsockbufsize: sndbuf_size determined as 524288
Connected to 192.168.50.220.
220 Welcome to DAN][, v3.3.3. Apple ][ Forever!
ftp_login: user \<null> pass \<null> host 192.168.50.220
---> USER anonymous
230 Ok
---> SYST
215 DAN][
Remote system type is DAN][.
---> FEAT
502 Failed
features[FEAT_FEAT] = 0
features[FEAT_MDTM] = -1
features[FEAT_MLST] = -1
features[FEAT_REST_STREAM] = -1
features[FEAT_SIZE] = -1
features[FEAT_TVFS] = -1
updatelocalcwd: got `/home/reidx'
ftp> ls
ftp: setsockopt SO_DEBUG (ignored): Permission denied
---> EPSV
421 Service not available, remote server has closed connection.
502 Failed
ftp>
```

If I swap back in the "working" 328p I see this:

```
reidx@GigaH270M:~$ ftp -a  -d 192.168.50.220
setupsockbufsize: rcvbuf_size determined as 1048576
setupsockbufsize: sndbuf_size determined as 524288
Connected to 192.168.50.220.
220 Welcome to DAN][, v3.3.3. Apple ][ Forever!
ftp_login: user \<null> pass \<null> host 192.168.50.220
---> USER anonymous
230 Ok
---> SYST
215 DAN][
Remote system type is DAN][.
---> FEAT
502 Failed
features[FEAT_FEAT] = 0
features[FEAT_MDTM] = -1
features[FEAT_MLST] = -1
features[FEAT_REST_STREAM] = -1
features[FEAT_SIZE] = -1
features[FEAT_TVFS] = -1
updatelocalcwd: got `/home/reidx'
ftp> ls
ftp: setsockopt SO_DEBUG (ignored): Permission denied
---> EPSV
502 Failed
disabling epsv4 for this connection
---> PASV
227 Entering Passive Mode (192,168,50,220,253,252)
---> LIST
150 Ok
drwx------ 1 DAN][ FAT 1 Jun 10 1977 SD1
drwx------ 1 DAN][ FAT 1 Jun 10 1977 SD2
226 Ok
ftp> cd sd1
---> CWD sd1
250 Ok
ftp> ls
ftp: setsockopt SO_DEBUG (ignored): Permission denied
---> PASV
227 Entering Passive Mode (192,168,50,220,253,252)
---> LIST
150 Ok
-rw------- 1 volume: SOSHDBOOT       16776704 Jun 10 1977 VOL00.PO
-rw------- 1 volume: V01.EMPTY.16MB  16776704 Jun 10 1977 VOL01.PO
-rw------- 1 volume: APPLE3.A2EMU      143360 Jun 10 1977 VOL02.PO
-rw------- 1 volume: BOOT.TEMPLATE   16776704 Jun 10 1977 VOL03.PO
-rw------- 1 volume: SOS.HORSES        143360 Jun 10 1977 VOL04.PO
-rw------- 1 volume: SOS.SONATA        143360 Jun 10 1977 VOL05.PO
-rw------- 1 volume: SOS.SPEAK         143360 Jun 10 1977 VOL06.PO
-rw------- 1 volume: V07.EMPTY.16MB  16776704 Jun 10 1977 VOL07.PO
-rw------- 1 volume: V08.EMPTY.16MB  16776704 Jun 10 1977 VOL08.PO
-rw------- 1 volume: V09.EMPTY.16MB  16776704 Jun 10 1977 VOL09.PO
-rw------- 1 volume: V0A.EMPTY.16MB  16776704 Jun 10 1977 VOL0A.PO
-rw------- 1 volume: V0B.EMPTY.16MB  16776704 Jun 10 1977 VOL0B.PO
-rw------- 1 volume: V0C.EMPTY.16MB  16776704 Jun 10 1977 VOL0C.PO
-rw------- 1 volume: V0D.EMPTY.16MB  16776704 Jun 10 1977 VOL0D.PO
-rw------- 1 volume: V0E.EMPTY.16MB  16776704 Jun 10 1977 VOL0E.PO
-rw------- 1 volume: V0F.EMPTY.16MB  16776704 Jun 10 1977 VOL0F.PO
226 Ok
ftp>
```

**Comment by rtrimbler** [comment]
One other thing I've noticed when things work correctly is that the LED on the Wiznet chip select line (D11) stays on as soon as the ftp connection is established. When it doesn't work, the LED flashes briefly when the connection starts, then stays off.

**Comment by ThorstenBr** [comment]
The D11 LED should be on continuously while an FTP session is active. The firmware is almost continuously polling the Wiznet module as soon as an FTP connection is established (meanwhile the connection to the Apple/6502 is frozen, until  FTP was disconnected). So when the LED is not on continuously, it has either already lost the FTP connection - or the firmware got stuck somewhere).

What happens on the Apple/6502 side when the D11 LED is off, despite the FTP connection (without triggering another RESET of course).
* Is the machine able to access volumes (so the ATMEGA is not stuck, but thinks the FTP connection is dropped, so it stopped polling the Wiznet module at high rate)?
* Or is the machine still unable to access disks? (Which suggests the ATMEGA is stuck somewhere - so neither FTP works, nor the 6502 volume access).

What exactly is the difference between the working and non working versions? Does it just depend on the specific sample of the 328p chip? Or does it depend on the uploaded binary/hex file?

**Comment by rtrimbler** [comment]
Behavior has become very intermittent. Right now, D11 stays on for several seconds. While it is on, ftp works as expected. When D11 goes off, the next ftp command results in "421 Service not available, remote server has closed connection." The Apple side is still happy to access the SD cards. So it seems like the ATMEGA is not stuck, but the ftp connection dropped. I'm going to try a different LAN cable.

**Comment by ThorstenBr** [comment]
Ok, it does sound a bit like more of a hardware issue... If not with the LAN cable, then maybe with the SPI cable - or the Wiznet module itself?

**Comment by rtrimbler** [comment]
Changing the LAN cable seems to have made a big difference. Looks like I need to re-wire my lab to replace the old cable. 

Forgot to answer the other question - the "working" 328p chip was programmed with the ISP shield from the source code. I checked the fuses (with an avrdude command line) and they are correct.  The other one (which now works too) was programmed on the XGecu with the hex file from the repo - after I corrected the fuse settings.

I did try 2 wiznet modules and 2 different SPI cables with similar intermittent results. (Prior to changing the LAN cable. Who ever suspects the cables?)

**Comment by ThorstenBr** [comment]
Haha, it's always the simple things making a lot of trouble (once one weeded out all the complex issues...). 
Glad the FTP issue also seems to be resolved now... :+1:

**Comment by rtrimbler** [comment]
Thank you for all the time you spent on my odd-ball issue yesterday, and for the detailed explanations that helped me understand where I went wrong at various steps. I have learned many new things through this project, not just Apple /// related - but arduinos, eproms, kicad, ftp, and ordering my first PCB's (even if they weren't my design). Your guidance is very much appreciated.

**Comment by ThorstenBr** [comment]
No problem, you're welcome! It's nice to see someone else tinkering with the Apple ///. Not too many people are still doing something with the Apple ///. There is few machines anyway, and most seem to be owned by collectors only, who just want to have one, rather than to be using it in any way...
